// This File contains vcmp constants.
enum Weapons {
    FIST,
    BRASS_KNUCKLES,
    SCREWDRIVER,
    GOLFCLUB,
    NITESTICK,
    KNIFE,
    BASEBALLBAT,
    HAMMER,
    MEATCLEVER,
    MACHETE,
    KATANA,
    CHAINSAW,
    GRENADES,
    REMOTEGRENADES,
    TEARGAS,
    MOLOTOV,
    MISSILE,
    COLT45,
    PYTHON,
    SHOTGUN,
    SPAZ,
    STUBBY,
    TEC9,
    UZI,
    INGRAM,
    MP5,
    M4,
    RUGER,
    SNIPER,
    LASERSNIPER,
    ROCKETLAUNCHER,
    FLAMETHROWER,
    M60,
    MINIGUN
};

const MAX_PLAYERS = 100
const MAX_VEHICLES = 1000
const MAX_OBJECTS = 3000
const MAX_PICKUPS = 2000
const MAX_SPRITES = 128
const MAX_TEXTDRAWS = 256

const NO_TEAM = 255
